app = "phoenix-analytics"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[env]
  PHX_HOST = "phoenix-analytics.fly.dev"
  PORT = "8080"
  MIX_ENV = "prod"
  ECTO_IPV6 = "true"
  ERL_AFLAGS = "-proto_dist inet6_tcp"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 800

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
