defmodule PhoenixAnalytics.Repo.Migrations.InitialSetup do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:variants, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :weight, :bigint, default: 50
      add :description, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :experiment_id, :uuid, null: false
    end

    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :email, :citext, null: false
      add :name, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")

    create table(:sites, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :domain, :text, null: false
      add :token, :text, null: false
      add :active, :boolean, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:sites, [:domain], name: "sites_unique_domain_index")

    create unique_index(:sites, [:token], name: "sites_unique_token_index")

    create table(:pageviews, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :session_hash, :text, null: false
      add :url, :text, null: false
      add :referrer, :text
      add :utm_source, :text
      add :utm_medium, :text
      add :utm_campaign, :text
      add :country, :text
      add :device_type, :text
      add :browser, :text
      add :os, :text
      add :duration_seconds, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :site_id,
          references(:sites,
            column: :id,
            name: "pageviews_site_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create index(:pageviews, [:session_hash])

    create index(:pageviews, [:site_id, :inserted_at])

    create table(:magic_tokens, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :token, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :used, :boolean, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "magic_tokens_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create index(:magic_tokens, [:inserted_at])

    create index(:magic_tokens, [:token], unique: true)

    create table(:experiments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:variants) do
      modify :experiment_id,
             references(:experiments,
               column: :id,
               name: "variants_experiment_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:experiments) do
      add :name, :text, null: false
      add :description, :text
      add :goal_event, :text, null: false
      add :status, :text, default: "draft"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :site_id,
          references(:sites,
            column: :id,
            name: "experiments_site_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create index(:experiments, [:site_id, :status])

    create table(:events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :session_hash, :text, null: false
      add :event_name, :text, null: false
      add :url, :text, null: false
      add :metadata, :map, default: %{}
      add :experiment_id, :uuid
      add :variant_name, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :site_id,
          references(:sites,
            column: :id,
            name: "events_site_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create index(:events, [:session_hash])

    create index(:events, [:site_id, :event_name, :inserted_at])

    create table(:assignments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :session_hash, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :experiment_id,
          references(:experiments,
            column: :id,
            name: "assignments_experiment_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :variant_id,
          references(:variants,
            column: :id,
            name: "assignments_variant_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create index(:assignments, [:experiment_id, :session_hash], unique: true)

    create unique_index(:assignments, [:experiment_id, :session_hash],
             name: "assignments_unique_session_experiment_index"
           )
  end

  def down do
    drop_if_exists unique_index(:assignments, [:experiment_id, :session_hash],
                     name: "assignments_unique_session_experiment_index"
                   )

    drop constraint(:assignments, "assignments_experiment_id_fkey")

    drop constraint(:assignments, "assignments_variant_id_fkey")

    drop_if_exists index(:assignments, [:experiment_id, :session_hash])

    drop table(:assignments)

    drop constraint(:events, "events_site_id_fkey")

    drop_if_exists index(:events, [:site_id, :event_name, :inserted_at])

    drop_if_exists index(:events, [:session_hash])

    drop table(:events)

    drop constraint(:experiments, "experiments_site_id_fkey")

    drop_if_exists index(:experiments, [:site_id, :status])

    alter table(:experiments) do
      remove :site_id
      remove :updated_at
      remove :inserted_at
      remove :status
      remove :goal_event
      remove :description
      remove :name
    end

    drop constraint(:variants, "variants_experiment_id_fkey")

    alter table(:variants) do
      modify :experiment_id, :uuid
    end

    drop table(:experiments)

    drop constraint(:magic_tokens, "magic_tokens_user_id_fkey")

    drop_if_exists index(:magic_tokens, [:token])

    drop_if_exists index(:magic_tokens, [:inserted_at])

    drop table(:magic_tokens)

    drop constraint(:pageviews, "pageviews_site_id_fkey")

    drop_if_exists index(:pageviews, [:site_id, :inserted_at])

    drop_if_exists index(:pageviews, [:session_hash])

    drop table(:pageviews)

    drop_if_exists unique_index(:sites, [:token], name: "sites_unique_token_index")

    drop_if_exists unique_index(:sites, [:domain], name: "sites_unique_domain_index")

    drop table(:sites)

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    drop table(:users)

    drop table(:variants)
  end
end
